# Generated by Django 5.2.5 on 2025-08-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(verbose_name='Text of Prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Date of Entry')),
                ('entry_text', models.TextField(verbose_name='Text of Entry')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyreviewweb.prompt')),
            ],
        ),
    ]
