# Generated by Django 5.2.5 on 2025-12-02 06:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreviewweb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-entry_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='entry_text',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='prompt_text',
        ),
        migrations.AddField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('summary_week', 'Weekly summary'), ('summary_month', 'Monthly summary'), ('summary_year', 'Yearly summary')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='entry',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='text',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dailyreviewweb.prompt'),
        ),
    ]
